export const sponsors = [
    { name: "mnvo.svg", title: "Ministry of Science and Higher Education", url: "https://www.gov.kz/memleket/entities/sci" },
    { name: "ministry-of-education.svg", title: "Ministry of Education", url: "https://www.gov.kz/memleket/entities/edu" },
    { name: "almaty-daryny.svg", title: "Almaty Daryny", url: "http://almaty.daryny.kz/" },
    { name: "nis.svg", title: "Nazarbayev Intellectual Schools", url: "https://nis.edu.kz/" },
    { name: "caravan.svg", title: "Caravan of Knowledge", url: "https://caravanofknowledge.com/" },
    { name: "chevron.svg", title: "Chevron", url: "https://www.chevron.com/" },
    { name: "aues.svg", title: "Almaty University of Energy and Communications", url: "https://aues.edu.kz/" },
    { name: "mephi.svg", title: "National Research Nuclear University MEPhI", url: "https://almaty.mephi.ru/" },
    { name: "beyond-curriculum.svg", title: "Beyond Curriculum", url: "https://bc-pf.org/" },
    { name: "el-umiti.svg", title: "El Umiti", url: "https://elumiti.kz/" },
    { name: "stemolympiads.svg", title: "STEMOlympiads", url: "https://stemolympiads.kz/" },
    { name: "lenovo.svg", title: "Lenovo", url: "https://www.lenovo.com/kz/ru/" },
    { name: "rphms.svg", title: "Republican Physics and Mathematics School", url: "https://fizmat.kz/" },
    { name: "ustem.svg", title: "USTEM Foundation", url: "https://www.instagram.com/ustem_foundation/" },
    { name: "wolfram-alpha.svg", title: "Wolfram Alpha", url: "https://www.wolframalpha.com/" },
];
